version: '3.9'

services:
  container:
    build: .
    ports:
      - "8080:8080"
    working_dir: /usr/service/
    volumes:
      - ../service:/usr/service
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t